version: "3.9"

services:
  mlops-api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: mlops_api_service
    ports:
      - "8000:8000"
    environment:
      - PDM_IGNORE_SAVED_PYTHON=1
      - DVC_PASSWORD=${DVC_PASSWORD}
    command: >
      bash -c "
        dvc remote modify origin-dags user katimanova &&
        dvc remote modify origin-dags password $DVC_PASSWORD &&
        pdm run dvc pull models/random_forest.pkl &&
        pdm run uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
      "