name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install PDM
      run: pip install pdm

    - name: Install dependencies
      run: pdm install

    - name: Run linters
      run: |
        pdm run black --check src tests
        pdm run flake8 src tests
        pdm run ruff check src tests
        pdm run mypy src

    - name: Build Docker image
      run: docker build -t mlops-titanic .

  publish-docker:
    needs: test-and-build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install PDM
      run: pip install pdm

    - name: Install dependencies
      run: pdm install

    - name: Build Python package
      run: pdm build

    - name: Publish Python package to GitHub Packages
      run: pdm publish --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
